### ISSUE TITLE
error: ordered comparison between pointer and zero

### ISSUE THREAD

**Issue by mxcai** [StoreyLab/terastructure#16]
When doing the `make' step in mac, it throws an error like this: 

`snp.cc:41:18: error: ordered comparison between pointer and zero
      ('char *' and 'int')
  assert (tmpbuf > 0);
          ~~~~~~ ^ ~
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE...
                        ^
snp.cc:106:17: error: ordered comparison between pointer and zero
      ('char *' and 'int')
        assert (tmpbuf > 0);
                ~~~~~~ ^ ~
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE...`

I used the mac installation version. Do you have any idea how to deal with this error?

Great thanks.

**Comment by whao89** [comment]
Can you pull and try again? Looks like newer versions Clang upgraded the shorthand I used there to an error. Unfortunately I don't have a mac so I can't test this myself, so we might have to go back and forth a few times here.

**Comment by mxcai** [comment]
Thank you for your update! Although some warnings are generated at `make' step, it works now. Checked with those generated by Linux version, I believe the outputs are correct.
