### ISSUE TITLE
Meaning of [ERR] in infer.log

### ISSUE THREAD

**Issue by variani** [StoreyLab/terastructure#18]
When I run the program on my dataset, I see "[ERR]" in the log file "infer.log". 
 
```
[Oct 15 13:52:35] [20155] [ERR] iteration = 465633 took 1227 secs
[Oct 15 13:52:35] [20155] [ERR] computing heldout likelihood @ 1227 secs
[Oct 15 13:52:38] [20155] [ERR] saving theta @ 1230 secs
[Oct 15 13:52:38] [20155] [ERR] done @ 1230 secs
```

Is it an error? If so, it would be helpful to know the details.

The output file "theta.txt" looks fine.

**Comment by whao89** [comment]
Not an error. "ERR" reflects the level of logging: https://github.com/StoreyLab/terastructure/blob/master/src/log.hh#L24. Long ago during development, we were setting `Logger::Level Env::level` at runtime to control how spammy infer.log was. Sorry if the message caused any confusion!

**Comment by variani** [comment]
That resolves all my concerns. Thank you for the quick reply!
