### ISSUE TITLE
improved documentation

### ISSUE THREAD

**Issue by whao89** [StoreyLab/terastructure#3]
especially with regards to `--compute-betas`

**Comment by premgopalan** [comment]
yes, please remove. also we need to remove variants of the algorithm A, B, C etc. -- i forget -- that are never used.

**Comment by whao89** [comment]
good point, i'll add that as a separate issue since it's kind of separate.

**Comment by Aquarius2016** [comment]
how does teraStructure generate a graph of distribution for theta?  By the way, how can I find the max likelihood score among the initialization from k=3 to N?

**Comment by whao89** [comment]
we generated the theta plots just drawing stacked bar plots in R (with no space between the bars). The validation likelihoods are in the file `validation.txt` associated with your run's output. It's the third column. You'll want to compare the last of those values for the different K you're interested in, ideally with a few reps.

**Comment by whao89** [comment]
added a wiki
